package libemail

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"net/smtp"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// SMTPAuthMock implements SMTPAuth
type SMTPAuthMock struct {
	t minimock.Tester

	funcNext          func(fromServer []byte, more bool) (toServer []byte, err error)
	inspectFuncNext   func(fromServer []byte, more bool)
	afterNextCounter  uint64
	beforeNextCounter uint64
	NextMock          mSMTPAuthMockNext

	funcStart          func(server *smtp.ServerInfo) (proto string, toServer []byte, err error)
	inspectFuncStart   func(server *smtp.ServerInfo)
	afterStartCounter  uint64
	beforeStartCounter uint64
	StartMock          mSMTPAuthMockStart
}

// NewSMTPAuthMock returns a mock for SMTPAuth
func NewSMTPAuthMock(t minimock.Tester) *SMTPAuthMock {
	m := &SMTPAuthMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.NextMock = mSMTPAuthMockNext{mock: m}
	m.NextMock.callArgs = []*SMTPAuthMockNextParams{}

	m.StartMock = mSMTPAuthMockStart{mock: m}
	m.StartMock.callArgs = []*SMTPAuthMockStartParams{}

	return m
}

type mSMTPAuthMockNext struct {
	mock               *SMTPAuthMock
	defaultExpectation *SMTPAuthMockNextExpectation
	expectations       []*SMTPAuthMockNextExpectation

	callArgs []*SMTPAuthMockNextParams
	mutex    sync.RWMutex
}

// SMTPAuthMockNextExpectation specifies expectation struct of the SMTPAuth.Next
type SMTPAuthMockNextExpectation struct {
	mock    *SMTPAuthMock
	params  *SMTPAuthMockNextParams
	results *SMTPAuthMockNextResults
	Counter uint64
}

// SMTPAuthMockNextParams contains parameters of the SMTPAuth.Next
type SMTPAuthMockNextParams struct {
	fromServer []byte
	more       bool
}

// SMTPAuthMockNextResults contains results of the SMTPAuth.Next
type SMTPAuthMockNextResults struct {
	toServer []byte
	err      error
}

// Expect sets up expected params for SMTPAuth.Next
func (mmNext *mSMTPAuthMockNext) Expect(fromServer []byte, more bool) *mSMTPAuthMockNext {
	if mmNext.mock.funcNext != nil {
		mmNext.mock.t.Fatalf("SMTPAuthMock.Next mock is already set by Set")
	}

	if mmNext.defaultExpectation == nil {
		mmNext.defaultExpectation = &SMTPAuthMockNextExpectation{}
	}

	mmNext.defaultExpectation.params = &SMTPAuthMockNextParams{fromServer, more}
	for _, e := range mmNext.expectations {
		if minimock.Equal(e.params, mmNext.defaultExpectation.params) {
			mmNext.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmNext.defaultExpectation.params)
		}
	}

	return mmNext
}

// Inspect accepts an inspector function that has same arguments as the SMTPAuth.Next
func (mmNext *mSMTPAuthMockNext) Inspect(f func(fromServer []byte, more bool)) *mSMTPAuthMockNext {
	if mmNext.mock.inspectFuncNext != nil {
		mmNext.mock.t.Fatalf("Inspect function is already set for SMTPAuthMock.Next")
	}

	mmNext.mock.inspectFuncNext = f

	return mmNext
}

// Return sets up results that will be returned by SMTPAuth.Next
func (mmNext *mSMTPAuthMockNext) Return(toServer []byte, err error) *SMTPAuthMock {
	if mmNext.mock.funcNext != nil {
		mmNext.mock.t.Fatalf("SMTPAuthMock.Next mock is already set by Set")
	}

	if mmNext.defaultExpectation == nil {
		mmNext.defaultExpectation = &SMTPAuthMockNextExpectation{mock: mmNext.mock}
	}
	mmNext.defaultExpectation.results = &SMTPAuthMockNextResults{toServer, err}
	return mmNext.mock
}

//Set uses given function f to mock the SMTPAuth.Next method
func (mmNext *mSMTPAuthMockNext) Set(f func(fromServer []byte, more bool) (toServer []byte, err error)) *SMTPAuthMock {
	if mmNext.defaultExpectation != nil {
		mmNext.mock.t.Fatalf("Default expectation is already set for the SMTPAuth.Next method")
	}

	if len(mmNext.expectations) > 0 {
		mmNext.mock.t.Fatalf("Some expectations are already set for the SMTPAuth.Next method")
	}

	mmNext.mock.funcNext = f
	return mmNext.mock
}

// When sets expectation for the SMTPAuth.Next which will trigger the result defined by the following
// Then helper
func (mmNext *mSMTPAuthMockNext) When(fromServer []byte, more bool) *SMTPAuthMockNextExpectation {
	if mmNext.mock.funcNext != nil {
		mmNext.mock.t.Fatalf("SMTPAuthMock.Next mock is already set by Set")
	}

	expectation := &SMTPAuthMockNextExpectation{
		mock:   mmNext.mock,
		params: &SMTPAuthMockNextParams{fromServer, more},
	}
	mmNext.expectations = append(mmNext.expectations, expectation)
	return expectation
}

// Then sets up SMTPAuth.Next return parameters for the expectation previously defined by the When method
func (e *SMTPAuthMockNextExpectation) Then(toServer []byte, err error) *SMTPAuthMock {
	e.results = &SMTPAuthMockNextResults{toServer, err}
	return e.mock
}

// Next implements SMTPAuth
func (mmNext *SMTPAuthMock) Next(fromServer []byte, more bool) (toServer []byte, err error) {
	mm_atomic.AddUint64(&mmNext.beforeNextCounter, 1)
	defer mm_atomic.AddUint64(&mmNext.afterNextCounter, 1)

	if mmNext.inspectFuncNext != nil {
		mmNext.inspectFuncNext(fromServer, more)
	}

	mm_params := &SMTPAuthMockNextParams{fromServer, more}

	// Record call args
	mmNext.NextMock.mutex.Lock()
	mmNext.NextMock.callArgs = append(mmNext.NextMock.callArgs, mm_params)
	mmNext.NextMock.mutex.Unlock()

	for _, e := range mmNext.NextMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.toServer, e.results.err
		}
	}

	if mmNext.NextMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmNext.NextMock.defaultExpectation.Counter, 1)
		mm_want := mmNext.NextMock.defaultExpectation.params
		mm_got := SMTPAuthMockNextParams{fromServer, more}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmNext.t.Errorf("SMTPAuthMock.Next got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmNext.NextMock.defaultExpectation.results
		if mm_results == nil {
			mmNext.t.Fatal("No results are set for the SMTPAuthMock.Next")
		}
		return (*mm_results).toServer, (*mm_results).err
	}
	if mmNext.funcNext != nil {
		return mmNext.funcNext(fromServer, more)
	}
	mmNext.t.Fatalf("Unexpected call to SMTPAuthMock.Next. %v %v", fromServer, more)
	return
}

// NextAfterCounter returns a count of finished SMTPAuthMock.Next invocations
func (mmNext *SMTPAuthMock) NextAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNext.afterNextCounter)
}

// NextBeforeCounter returns a count of SMTPAuthMock.Next invocations
func (mmNext *SMTPAuthMock) NextBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNext.beforeNextCounter)
}

// Calls returns a list of arguments used in each call to SMTPAuthMock.Next.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmNext *mSMTPAuthMockNext) Calls() []*SMTPAuthMockNextParams {
	mmNext.mutex.RLock()

	argCopy := make([]*SMTPAuthMockNextParams, len(mmNext.callArgs))
	copy(argCopy, mmNext.callArgs)

	mmNext.mutex.RUnlock()

	return argCopy
}

// MinimockNextDone returns true if the count of the Next invocations corresponds
// the number of defined expectations
func (m *SMTPAuthMock) MinimockNextDone() bool {
	for _, e := range m.NextMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.NextMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterNextCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcNext != nil && mm_atomic.LoadUint64(&m.afterNextCounter) < 1 {
		return false
	}
	return true
}

// MinimockNextInspect logs each unmet expectation
func (m *SMTPAuthMock) MinimockNextInspect() {
	for _, e := range m.NextMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SMTPAuthMock.Next with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.NextMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterNextCounter) < 1 {
		if m.NextMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to SMTPAuthMock.Next")
		} else {
			m.t.Errorf("Expected call to SMTPAuthMock.Next with params: %#v", *m.NextMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcNext != nil && mm_atomic.LoadUint64(&m.afterNextCounter) < 1 {
		m.t.Error("Expected call to SMTPAuthMock.Next")
	}
}

type mSMTPAuthMockStart struct {
	mock               *SMTPAuthMock
	defaultExpectation *SMTPAuthMockStartExpectation
	expectations       []*SMTPAuthMockStartExpectation

	callArgs []*SMTPAuthMockStartParams
	mutex    sync.RWMutex
}

// SMTPAuthMockStartExpectation specifies expectation struct of the SMTPAuth.Start
type SMTPAuthMockStartExpectation struct {
	mock    *SMTPAuthMock
	params  *SMTPAuthMockStartParams
	results *SMTPAuthMockStartResults
	Counter uint64
}

// SMTPAuthMockStartParams contains parameters of the SMTPAuth.Start
type SMTPAuthMockStartParams struct {
	server *smtp.ServerInfo
}

// SMTPAuthMockStartResults contains results of the SMTPAuth.Start
type SMTPAuthMockStartResults struct {
	proto    string
	toServer []byte
	err      error
}

// Expect sets up expected params for SMTPAuth.Start
func (mmStart *mSMTPAuthMockStart) Expect(server *smtp.ServerInfo) *mSMTPAuthMockStart {
	if mmStart.mock.funcStart != nil {
		mmStart.mock.t.Fatalf("SMTPAuthMock.Start mock is already set by Set")
	}

	if mmStart.defaultExpectation == nil {
		mmStart.defaultExpectation = &SMTPAuthMockStartExpectation{}
	}

	mmStart.defaultExpectation.params = &SMTPAuthMockStartParams{server}
	for _, e := range mmStart.expectations {
		if minimock.Equal(e.params, mmStart.defaultExpectation.params) {
			mmStart.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStart.defaultExpectation.params)
		}
	}

	return mmStart
}

// Inspect accepts an inspector function that has same arguments as the SMTPAuth.Start
func (mmStart *mSMTPAuthMockStart) Inspect(f func(server *smtp.ServerInfo)) *mSMTPAuthMockStart {
	if mmStart.mock.inspectFuncStart != nil {
		mmStart.mock.t.Fatalf("Inspect function is already set for SMTPAuthMock.Start")
	}

	mmStart.mock.inspectFuncStart = f

	return mmStart
}

// Return sets up results that will be returned by SMTPAuth.Start
func (mmStart *mSMTPAuthMockStart) Return(proto string, toServer []byte, err error) *SMTPAuthMock {
	if mmStart.mock.funcStart != nil {
		mmStart.mock.t.Fatalf("SMTPAuthMock.Start mock is already set by Set")
	}

	if mmStart.defaultExpectation == nil {
		mmStart.defaultExpectation = &SMTPAuthMockStartExpectation{mock: mmStart.mock}
	}
	mmStart.defaultExpectation.results = &SMTPAuthMockStartResults{proto, toServer, err}
	return mmStart.mock
}

//Set uses given function f to mock the SMTPAuth.Start method
func (mmStart *mSMTPAuthMockStart) Set(f func(server *smtp.ServerInfo) (proto string, toServer []byte, err error)) *SMTPAuthMock {
	if mmStart.defaultExpectation != nil {
		mmStart.mock.t.Fatalf("Default expectation is already set for the SMTPAuth.Start method")
	}

	if len(mmStart.expectations) > 0 {
		mmStart.mock.t.Fatalf("Some expectations are already set for the SMTPAuth.Start method")
	}

	mmStart.mock.funcStart = f
	return mmStart.mock
}

// When sets expectation for the SMTPAuth.Start which will trigger the result defined by the following
// Then helper
func (mmStart *mSMTPAuthMockStart) When(server *smtp.ServerInfo) *SMTPAuthMockStartExpectation {
	if mmStart.mock.funcStart != nil {
		mmStart.mock.t.Fatalf("SMTPAuthMock.Start mock is already set by Set")
	}

	expectation := &SMTPAuthMockStartExpectation{
		mock:   mmStart.mock,
		params: &SMTPAuthMockStartParams{server},
	}
	mmStart.expectations = append(mmStart.expectations, expectation)
	return expectation
}

// Then sets up SMTPAuth.Start return parameters for the expectation previously defined by the When method
func (e *SMTPAuthMockStartExpectation) Then(proto string, toServer []byte, err error) *SMTPAuthMock {
	e.results = &SMTPAuthMockStartResults{proto, toServer, err}
	return e.mock
}

// Start implements SMTPAuth
func (mmStart *SMTPAuthMock) Start(server *smtp.ServerInfo) (proto string, toServer []byte, err error) {
	mm_atomic.AddUint64(&mmStart.beforeStartCounter, 1)
	defer mm_atomic.AddUint64(&mmStart.afterStartCounter, 1)

	if mmStart.inspectFuncStart != nil {
		mmStart.inspectFuncStart(server)
	}

	mm_params := &SMTPAuthMockStartParams{server}

	// Record call args
	mmStart.StartMock.mutex.Lock()
	mmStart.StartMock.callArgs = append(mmStart.StartMock.callArgs, mm_params)
	mmStart.StartMock.mutex.Unlock()

	for _, e := range mmStart.StartMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.proto, e.results.toServer, e.results.err
		}
	}

	if mmStart.StartMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStart.StartMock.defaultExpectation.Counter, 1)
		mm_want := mmStart.StartMock.defaultExpectation.params
		mm_got := SMTPAuthMockStartParams{server}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStart.t.Errorf("SMTPAuthMock.Start got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStart.StartMock.defaultExpectation.results
		if mm_results == nil {
			mmStart.t.Fatal("No results are set for the SMTPAuthMock.Start")
		}
		return (*mm_results).proto, (*mm_results).toServer, (*mm_results).err
	}
	if mmStart.funcStart != nil {
		return mmStart.funcStart(server)
	}
	mmStart.t.Fatalf("Unexpected call to SMTPAuthMock.Start. %v", server)
	return
}

// StartAfterCounter returns a count of finished SMTPAuthMock.Start invocations
func (mmStart *SMTPAuthMock) StartAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStart.afterStartCounter)
}

// StartBeforeCounter returns a count of SMTPAuthMock.Start invocations
func (mmStart *SMTPAuthMock) StartBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStart.beforeStartCounter)
}

// Calls returns a list of arguments used in each call to SMTPAuthMock.Start.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStart *mSMTPAuthMockStart) Calls() []*SMTPAuthMockStartParams {
	mmStart.mutex.RLock()

	argCopy := make([]*SMTPAuthMockStartParams, len(mmStart.callArgs))
	copy(argCopy, mmStart.callArgs)

	mmStart.mutex.RUnlock()

	return argCopy
}

// MinimockStartDone returns true if the count of the Start invocations corresponds
// the number of defined expectations
func (m *SMTPAuthMock) MinimockStartDone() bool {
	for _, e := range m.StartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StartMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStartCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStart != nil && mm_atomic.LoadUint64(&m.afterStartCounter) < 1 {
		return false
	}
	return true
}

// MinimockStartInspect logs each unmet expectation
func (m *SMTPAuthMock) MinimockStartInspect() {
	for _, e := range m.StartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SMTPAuthMock.Start with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StartMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStartCounter) < 1 {
		if m.StartMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to SMTPAuthMock.Start")
		} else {
			m.t.Errorf("Expected call to SMTPAuthMock.Start with params: %#v", *m.StartMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStart != nil && mm_atomic.LoadUint64(&m.afterStartCounter) < 1 {
		m.t.Error("Expected call to SMTPAuthMock.Start")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *SMTPAuthMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockNextInspect()

		m.MinimockStartInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *SMTPAuthMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *SMTPAuthMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockNextDone() &&
		m.MinimockStartDone()
}
